language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.22.0

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y binutils-dev libunwind8-dev

script:
  # The standard linker fails to link the fuzzing infrastructure but
  # gold seems to handle it.
  # See https://github.com/rust-lang/rust/issues/53945
  - export RUSTFLAGS='-Clink-arg=-fuse-ld=gold'
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --verbose --features=serde-feature
  - cargo test --verbose --features=serde-feature
  - if [ "$(rustup show | grep default | grep stable)" != "" ]; then cd fuzz && cargo test --verbose && ./travis-fuzz.sh; fi
