[package]
name = "rust-ocean"
version = "0.6.0"
authors = ["Andrew Poelstra <apoelstra@blockstream.com>", "Nikolaos Kostoulas <nikolaos@commerceblock.com"]
description = "Library with support for de/serialization, parsing and executing on data structures and network messages related to Ocean"

license = "CC0-1.0"
homepage = "https://github.com/commerceblock/rust-ocean/"
repository = "https://github.com/commerceblock/rust-ocean/"

[features]
"serde-feature" = [
    "bitcoin/serde",
    "bitcoin_hashes/serde",
    "serde"
]
"fuzztarget" = []

[dependencies]
bitcoin_hashes = "0.3.0"
secp256k1 = "0.12.0"

[dependencies.bitcoin]
version = "0.17.0"

[dependencies.serde]
version = "1.0"
optional = true

